/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserQueryGUIDemo;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;


/**
 *
 * @author soyebahmed
 */
public class userSearchResultsGUI extends javax.swing.JFrame {

    /**
     * Creates new form userSearchResultsGUI
     */
    public userSearchResultsGUI() {
        initComponents();
        addTableHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    
    DefaultTableModel model;
    
    
    public void addTableHeader(){
        
             //add Dynamic Data
        List data = new ArrayList();
        
        //add 4 data
        data.add("Photo");
        data.add("Product Name");
        data.add("Price");
        data.add("Avalability");
        
              
        data.add("image.png");
        data.add("Rolex");
        data.add("18$");
        data.add("yes");
        
        data.add("image2.jpg");
        data.add("Role");
        data.add("12$");
        data.add("yes");
        
        data.add("image.png");
        data.add("Rolex");
        data.add("18$");
        data.add("yes");
        
        data.add("image2.jpg");
        data.add("Role");
        data.add("12$");
        data.add("yes");
        
        data.add("image.png");
        data.add("Rolex");
        data.add("18$");
        data.add("yes");

        final Object colNames[] = {"", data.get(0).toString(), data.get(1).toString(), data.get(2).toString(), data.get(3).toString()};
        
        
        model = new DefaultTableModel(null, colNames){
                      public Class<?> getColumnClass(int column){
                        switch(column){
                        case 0:
                          return Boolean.class;
                        case 1:
                          return JLabel.class;
                        case 2:
                          return String.class;
                        case 3:
                          return String.class;
                        case 4:
                          return String.class;
                        case 5:
                          return String.class;
                        case 6:
                          return String.class;
                        case 7:
                          return String.class;

                          default:
                            return String.class;
                        }
                      }

                      public boolean isCellEditable(int row, int column){
                            switch (column) {
                            case 0:
                                return true;
                            default:
                                return false;
                         }
                     }
                };  
        

        
        jTable1.setModel(model); 
        
        int column = data.size()/4;
        System.out.println(column);
        
        //THE ROW
        for(int i=0;i<column-1;i++){
            
            int currentRow = 4*i+4;
            //resize image dynamicallt from local folder    
            JLabel imageLabel = new JLabel();
            ImageIcon icon = new ImageIcon(data.get(currentRow).toString());
            Image img = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(img));       
            
            //add data informtaion to the table
            model.addRow(new Object[]{false,imageLabel,data.get(currentRow+1).toString()
                      , data.get(currentRow+2).toString(), data.get(currentRow+3).toString()});
            }
        
            //add image dynamicallt from local folder    
            int BOOLEAN_COL = 0;
            jTable1.setAutoCreateRowSorter(true);
            jTable1.setFillsViewportHeight(true);
            jTable1.getColumn("Photo").setCellRenderer(new CellRenderer());
            TableColumn tc = jTable1.getColumnModel().getColumn(BOOLEAN_COL);

            tc.setHeaderRenderer(new SelectAllHeader(jTable1, BOOLEAN_COL));
        
    }
    
    class CellRenderer implements TableCellRenderer {
 
        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {
 
            TableColumn tb = jTable1.getColumn("Photo");
            tb.setMaxWidth(60);
            tb.setMinWidth(60);
 
            jTable1.setRowHeight(60);
 
            return (Component) value;
        }
 
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ImageIcon icon = new ImageIcon(getClass().getResource("");
            jTable1 = new javax.swing.JTable();
            jLabel1 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jComboBox1 = new javax.swing.JComboBox<>();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Search Result\n");
            setBounds(new java.awt.Rectangle(500, 120, 500, 600));
            setMinimumSize(new java.awt.Dimension(500, 600));
            setResizable(false);
            getContentPane().setLayout(null);

            jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
            ));
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jTable1);

            getContentPane().add(jScrollPane1);
            jScrollPane1.setBounds(-2, 85, 500, 290);

            jLabel1.setText("Search Results");
            getContentPane().add(jLabel1);
            jLabel1.setBounds(200, 30, 110, 40);

            jButton1.setText("Download");
            jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton1MouseClicked(evt);
                }
            });
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton1);
            jButton1.setBounds(200, 450, 107, 29);

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Data", "Selected Data" }));
            jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox1ActionPerformed(evt);
                }
            });
            getContentPane().add(jComboBox1);
            jComboBox1.setBounds(30, 450, 150, 27);

            pack();
        }// </editor-fold>//GEN-END:initComponents
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        
        if (evt.getClickCount() == 2) { 
            
            JTable target = (JTable)evt.getSource();
            int SelectedRowIndex = jTable1.getSelectedRow();
            model = (DefaultTableModel) jTable1.getModel();
            String first_name = model.getValueAt(SelectedRowIndex, 1).toString();
           
            JOptionPane.showMessageDialog(null, model.getValueAt(SelectedRowIndex, 1).toString());

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //GET SELECTED ROW
        for(int i=0;i<jTable1.getRowCount();i++){
          Boolean checked=Boolean.valueOf(jTable1.getValueAt(i, 0).toString());
          String col=jTable1.getValueAt(i, 1).toString();

          //DISPLAY
          if(checked){
            JOptionPane.showMessageDialog(null, col);
          }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userSearchResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userSearchResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userSearchResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userSearchResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userSearchResultsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}


